%% Import data from text file.
% Script for importing data from the following text files:
%
%    C:\Users\Radu\Desktop\neuronhw3\
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2013/10/31 00:48:52
close all;clc; clear all;
%% Initialize variables.
filename{1} = 'C:\Users\JuanandKimi\Desktop\New folder\d1_1.dat';
filename{2} = 'C:\Users\JuanandKimi\Desktop\New folder\d2_1.dat';
filename{3} = 'C:\Users\JuanandKimi\Desktop\New folder\d1_2.dat';
filename{4} = 'C:\Users\JuanandKimi\Desktop\New folder\d2_2.dat';
delimiter = '';

%% Format string for each line of text:
%   column1: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%[^\n\r]';

%% Open the text file.
for a = 1:4
    fileID{a} = fopen(filename{a},'r');
end

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
for a = 1:4
dataArray{a} = textscan(fileID{a}, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);
fclose(fileID{a});
end

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
for a = 1:4
    data{a} = dataArray{a}{:, 1};
end
%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

%%
d = logspace(-1,1,20);
figure(1);
for a = 1:4
loglog(d(end:-1:1),abs(data{a}));
hold all;
end
legend('fiber 1 @ node','fiber 2 @ node','fiber 1 @ internode','fiber 2 @ internode',0)

figure(2);
for a = 1:4
semilogx(d(end:-1:1),abs(data{a}));
hold all;
end
legend('fiber 1 @ node','fiber 2 @ node','fiber 1 @ internode','fiber 2 @ internode',0)

%%Problem 1

